#!/bin/bash

# Script for win10
if [[ $1 == "win10" ]]; then
   if [[ $2 == "prepare" ]]; then
        /bin/vfio-startup.sh 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
   fi

   if [[ $2 == "release" ]]; then
        /bin/vfio-teardown.sh 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
   fi
fi

