#!/bin/sh

# Script for win10
if [[ $1 == "win10" ]]; then
   if [[ $2 == "prepare" ]]; then
	/bin/polaris-vfio-startup.sh
   fi

   if [[ $2 == "release" ]]; then
	/bin/polaris-vfio-teardown.sh
   fi
fi
